# Generated by Django 5.0.6 on 2024-07-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_city_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='description',
        ),
        migrations.AddField(
            model_name='city',
            name='popular',
            field=models.CharField(default='nothing', max_length=600),
            preserve_default=False,
        ),
    ]
