# Generated by Django 5.0.6 on 2024-07-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_prediction_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='photo_path',
            field=models.URLField(default='none'),
            preserve_default=False,
        ),
    ]
